name       : python-pypeg2
version    : 2.15.2
release    : 4
source     :
    - https://pypi.python.org/packages/f9/bd/10398e2c2d2070cc8a9c7153abfbd4ddb2895a2c52a32722ab8689e0cc7d/pyPEG2-2.15.2.tar.gz : 2b2d4f80d8e1a9370b2a91f4a25f4abf7f69b85c8da84cd23ec36451958a1f6d
license    : GPL-2.0
component  : programming.python
summary    : An intrinsic PEG Parser-Interpreter for Python
description: |
    An intrinsic PEG Parser-Interpreter for Python
build      : |
    %python3_setup
install    : |
    %python3_install
